### ISSUE TITLE
Request: Give option to turn off health/mana values

### ISSUE THREAD

**Issue by ZetoxZ** [wardz/FocusFrame#10]
Issue template
you only need to fill in the ones applicable to your issue:

Possible to give option to turn off status bar text eg health and mana numbers?

**Comment by wardz** [comment]
You can turn them off by toggling "Status Bar Text" under escape -> interface options, or would you like to only have the text disabled for the focus frame but enabled for other unit frames?

**Comment by ZetoxZ** [comment]
"would you like to only have the text disabled for the focus frame but enabled for other unit frames?
"

Yes. The reasoning being I have a mod "CleanPlayerFrame" which has better text centered . It's functionality is hooked into the Blizzard option of showing status text for HP mana.
SO on a rogue I have to have it showing for energy purposes 0/100 energy etc etc.
 But do not need to see status text on focus

**Comment by wardz** [comment]
Ah I see. Added an option for it now. (`/foption statustext`). Closing.

**Comment by ZetoxZ** [comment]
You're awesome!! Thanks so much 💯
