### ISSUE TITLE
Request: Cast bar to go to Main Target Frame

### ISSUE THREAD

**Issue by ZetoxZ** [wardz/FocusFrame#11]
Requesting it possible to have option for enabling cast bar for target frame also!

**Comment by wardz** [comment]
Added it as a seperate downloadable [plugin/addon here.](https://github.com/wardz/FocusFrame_TargetCastbar)
(I didn't wanna make it a built in option as it'd create too much bloat for users that don't need it.)

**Comment by ZetoxZ** [comment]
Thank you very much!!! 💯
