### ISSUE TITLE
Raidmarks

### ISSUE THREAD

**Issue by Meridaw** [wardz/FocusFrame#15]
Can you set focus a raidmark? like if your assigned to Polymorph moon, you set focus to Moon, then just /fcast Polymorph and it will Poly what ever target who got the Moon mark.

I found this macro for targeting raid marked enemy .

/run for i=1,13 do TargetNearestEnemy();if GetRaidTargetIndex("target")==X then do return;end;end;end;

Underlined characters: 13 represents the number of mobs to cycle through. Increase it to suit your needs. X represents the number of the raid target index. (8 is skull etc)

8 = Skull
7 = Cross
6 = Square
5 = Moon
4 = Triangle
3 = Purple
2 = Circle
1 = Star

**Comment by wardz** [comment]
So a mode like this?
```
/clearfocus
/focus <Whatever unit has moon>
/fcast Polymorph
```

Just curious, is this intended for PvP or PvE?

**Comment by Meridaw** [comment]
Not focus whatever unit has moon, but set the mark, so your focus cast macro will check for the Moon when you try to poly. Maybe like /fset Moon or /fset 5.
It`s for PVE mainly, i dont think you can raidmark players in pvp.

Best not make it /fcast i guess, so you dont just start poly on random targets, when the mod cycle through them. 
Maybe /mcast Polymorph, or add the number of mobs to cycle through /mcast10 Polymorph.

**Comment by wardz** [comment]
Ah I see, didn't notice your edit at first. I can for sure add a slash command for setting raid mark on your focus (You already can by right clicking focus frame so should be quick to add).

I'll have to investigate cycling through multiple enemies and detecting the raid mark though. I recall there was some issues with it before when I tested it like it only works if your camera is facing the unit, and it doesn't work in function events.

You can try if this works in the meantime:
`/run local u=UnitName("target")for i=1,13 do TargetNearestEnemy();if GetRaidTargetIndex("target")==5 then do fcast("Polymorph")TargetByName(u,true) return;end;end;end;`

**Comment by Meridaw** [comment]
Not sure if this could be relevant to making it work better, but this line Increases your tab target range.
 
/console targetNearestDistance 50

(max value is 50 yards)

**Comment by wardz** [comment]
Pretty close, seems like targetNearestDistanceRadius fixes it  👍

Added two new slash commands in commit above, `/fmark 5` for setting focus raid mark using icon indices. And `/fmcast ` for prioritizing raid marked targets, which can be used like this:
Polymorph only Moon:
`/fmcast 5 Polymorph`

Polymorph only Star, cycle 15 targets (default is 10)
`/fmcast 1 Polymorph 15`

If you're not in a group it'll default back to fcast().
This is still work in progress.

Edit: Just noticed having spaces in ability names screws it up, will fix later today.

Edit2: Fixed it now + some other issues, but you can no longer include cycle amount after ability name.

**Comment by Meridaw** [comment]
That is great news :100: 

> If you're not in a group it'll default back to fcast().
This is still work in progress.

It should default back to normal if you don't have focus as well, but i guess you already did that.

> Edit2: Fixed it now + some other issues, but you can no longer include cycle amount after ability name.

Can you do it when you set the focus mark? /fmark 5 15

**Comment by wardz** [comment]
Probably better to have it as an option, that way you only have to do it once and it still works if you set marks without using `/fmark`. Against mobs you most likely don't want to always use fmark anyways since it will target & mark a random mob when they have exact same name.

`/foption tarcycles 15` to change in latest commit. (min 1, max 49, seems reasonable enough)

> It should default back to normal if you don't have focus as well, but i guess you already did that.

You can add "-target" at the end of a spell name and it'll always use the ability on your current target if you have no focus.
I.e: `/fmcast 5 Polymorph(rank 1)-target` This will cast on focus with moon if in group, else on focus if exists, else on target.

**Comment by Meridaw** [comment]
It sounds perfect. :+1: 
Is it possible to make a macro that focus target, and clearfocus, if you already got a focus target?

**Comment by wardz** [comment]
You can use this:
`/run SlashCmdList[FocusCore:FocusExists() and "CLEARFOCUS" or "FOCUS"]()`
or trigger `/focus` while not having a target, then it auto calls clearfocus.


Don't think there's anything left to add for `/fmcast` so closing thread.
Feel free to open a new one if you notice any issues or bugs with it.
