### ISSUE TITLE
[Suggestion] Add support for clickcasting

### ISSUE THREAD

**Issue by lurexx** [wardz/FocusFrame#4]
Add support for clickcasting through luna's inbuilt clickcasting and clique

**Comment by wardz** [comment]
Clique support is not possible because it only relies on unit ids instead of unit names. (There is no focus unit id in vanilla)

Will try to add luna clickcasting for next non-minor release.

**Comment by lurexx** [comment]
Thank you!

**Comment by wardz** [comment]
Now added in v1.1.0.
