### ISSUE TITLE
Focus target is cleared on death

### ISSUE THREAD

**Issue by llacczy** [wardz/FocusFrame#6]
Hi i was testing the addon in some battlegrounds and the focus is cleared on player death, limiting the usefulness for the addon. Other than that it was very useful.
Please consider keeping the focus after death if it is possible.
(also keeping the focus on loading screen)

**Comment by Xistens** [comment]
If this should be implemented then at least make it optional. Can't personally see any use of keeping focus after death

**Comment by wardz** [comment]
I can make an option for it, but focus buffs will still have to be cleared due to API limitations in wow.

**Comment by wardz** [comment]
Added in 1.1.2 release.

**Comment by llacczy** [comment]
thanks it is really useful
