### ISSUE TITLE
LUA Error when damaging multiple targets

### ISSUE THREAD

**Issue by dinkletron** [wardz/FocusFrame#7]
![capture](https://user-images.githubusercontent.com/29308094/26980061-1d59a8f8-4d70-11e7-8a18-d19cb25b2770.JPG)
I'm getting this lua error even when I am not actually using a focus. Just in general, if I throw up a dot on two separate targets (same name, or different names), this pops up.

**Comment by wardz** [comment]
Thanks. Should be fixed now.
