### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by roanaes** [wardz/FocusFrame#9]
/focus and /clearfocus not working so basically its unusable for me x( 

I'm still able to use /mfocus function lol

Tested on Kronos and Retro.

**Comment by wardz** [comment]
This addon only supports Elysium servers, but I did test it on Kronos right now and it seems to work fine for me. Maybe you have an addon that interferes with FocusFrame? (i.e ClassicFocus) See if it still happens with all addons disabled except for FocusFrame.

Also just incase, FocusFrame only works with the english game client.
